"""Removed unnecesary theme_mode from restaurant

Revision ID: 070719cb749c
Revises: eff03be7f8bd
Create Date: 2025-11-20 18:50:21.496308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '070719cb749c'
down_revision: Union[str, Sequence[str], None] = 'eff03be7f8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'theme_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('theme_mode', postgresql.ENUM('LIGHT', 'DARK', 'SYSTEM', name='thememode'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
