"""add currency column to country table

Revision ID: 0a0aa8500f84
Revises: 6ad5655570ee
Create Date: 2025-11-19 20:49:48.049538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0aa8500f84'
down_revision: Union[str, Sequence[str], None] = '6ad5655570ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('currency', sa.String(length=4), nullable=False))
    op.create_unique_constraint(None, 'country', ['currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'currency')
    # ### end Alembic commands ###
