"""removed unique from phone code in country table

Revision ID: 44068db9e76a
Revises: 8af435584c40
Create Date: 2025-11-19 21:21:35.689957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44068db9e76a'
down_revision: Union[str, Sequence[str], None] = '8af435584c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('country_phone_code_key'), 'country', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('country_phone_code_key'), 'country', ['phone_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
