"""currency name and country name char count increased to 255

Revision ID: 5be1e64f973b
Revises: 6eebad02f0f5
Create Date: 2025-11-19 20:57:43.764142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be1e64f973b'
down_revision: Union[str, Sequence[str], None] = '6eebad02f0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('country', 'currency_name',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'currency_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
