"""rename currency to currency_code and added currency name and currency symbol

Revision ID: 6eebad02f0f5
Revises: 0a0aa8500f84
Create Date: 2025-11-19 20:56:31.430917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eebad02f0f5'
down_revision: Union[str, Sequence[str], None] = '0a0aa8500f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('currency_code', sa.String(length=4), nullable=False))
    op.add_column('country', sa.Column('currency_symbol', sa.String(length=4), nullable=False))
    op.add_column('country', sa.Column('currency_name', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('country_currency_key'), 'country', type_='unique')
    op.drop_column('country', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('currency', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('country_currency_key'), 'country', ['currency'], postgresql_nulls_not_distinct=False)
    op.drop_column('country', 'currency_name')
    op.drop_column('country', 'currency_symbol')
    op.drop_column('country', 'currency_code')
    # ### end Alembic commands ###
