"""changed char counts of fields in country table

Revision ID: 8af435584c40
Revises: 5be1e64f973b
Create Date: 2025-11-19 21:16:24.264237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af435584c40'
down_revision: Union[str, Sequence[str], None] = '5be1e64f973b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('country', 'currency_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('country', 'currency_symbol',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('country', 'phone_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'phone_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('country', 'currency_symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('country', 'currency_code',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('country', 'code',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###
