"""Fixed Restaurant relationship issues with user table to make it one to many

Revision ID: eff03be7f8bd
Revises: b773042ddeee
Create Date: 2025-11-20 18:48:44.727933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff03be7f8bd'
down_revision: Union[str, Sequence[str], None] = 'b773042ddeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('restaurant_user_id_key'), 'restaurant', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('restaurant_user_id_key'), 'restaurant', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
